name: Build
on:
  push:
    tags: 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Cache automagic
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Build
        run: |
          sudo apt install -y libxml2-dev libxslt1-dev
          python3 -m venv /tmp/my-build
          . /tmp/my-build/bin/activate
          pip install --upgrade pip
          pip install -r $GITHUB_WORKSPACE/requirements.txt
          pip install statmake
          bash $GITHUB_WORKSPACE/sources/build.sh

      - name: Pack
        run: |
          sudo apt-get install -y zip
          cd $GITHUB_WORKSPACE/fonts
          mv ../LICENSE.txt ../README.md .
          zip -r /tmp/my-build/roboto-mono.zip .

      - uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: /tmp/my-build/roboto-mono.zip

  release:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: my-artifact
          path: /tmp/my-build

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

      - name: Upload Artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /tmp/my-build/roboto-mono.zip
          asset_name: roboto-mono.zip
          asset_content_type: application/zip
